# Generated by Django 2.2.1 on 2019-06-12 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_auto_20190611_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 6, 12)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 6, 12)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 7, 34, 43, 829574)),
        ),
    ]
