# Generated by Django 2.2.1 on 2019-06-12 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_auto_20190612_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(default='00a00000', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='driver_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 9, 50, 37, 127045)),
        ),
    ]
