# Generated by Django 2.2.1 on 2019-06-12 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_auto_20190612_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='customer_score',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='driver_score',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 10, 3, 39, 429533)),
        ),
    ]
