# Generated by Django 2.2.1 on 2019-06-12 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0011_auto_20190612_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='id',
        ),
        migrations.AddField(
            model_name='discount',
            name='customer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taxi.Customer'),
        ),
        migrations.AlterField(
            model_name='score',
            name='customer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='driver_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 11, 26, 47, 22723)),
        ),
    ]
