# Generated by Django 2.2.1 on 2019-06-12 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0012_auto_20190612_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 14, 26, 13, 48674)),
        ),
    ]
